package engine.graphics.gl.buffer;

import org.lwjgl.opengl.*;

public enum GLBufferType {
    ARRAY_BUFFER(GL15.GL_ARRAY_BUFFER),
    ELEMENT_ARRAY_BUFFER(GL15.GL_ELEMENT_ARRAY_BUFFER),
    PIXEL_PACK_BUFFER(GL21.GL_PIXEL_PACK_BUFFER),
    PIXEL_UNPACK_BUFFER(GL21.GL_PIXEL_UNPACK_BUFFER),
    TRANSFORM_FEEDBACK_BUFFER(GL30.GL_TRANSFORM_FEEDBACK_BUFFER),
    UNIFORM_BUFFER(GL31.GL_UNIFORM_BUFFER),
    TEXTURE_BUFFER(GL31.GL_TEXTURE_BUFFER),
    COPY_READ_BUFFER(GL31.GL_COPY_READ_BUFFER),
    COPY_WRITE_BUFFER(GL31.GL_COPY_WRITE_BUFFER),
    DRAW_INDIRECT_BUFFER(GL40.GL_DRAW_INDIRECT_BUFFER),
    ATOMIC_COUNTER_BUFFER(GL42.GL_ATOMIC_COUNTER_BUFFER),
    DISPATCH_INDIRECT_BUFFER(GL43.GL_DISPATCH_INDIRECT_BUFFER),
    SHADER_STORAGE_BUFFER(GL43.GL_SHADER_STORAGE_BUFFER),
    PARAMETER_BUFFER(GL46.GL_PARAMETER_BUFFER);

    public final int gl;

    GLBufferType(int gl) {
        this.gl = gl;
    }
}
