package engine.graphics.vulkan.shader;

import org.lwjgl.vulkan.VK10;

public enum ShaderType {
    VERTEX_SHADER(VK10.VK_PIPELINE_STAGE_VERTEX_SHADER_BIT, VK10.VK_SHADER_STAGE_VERTEX_BIT),
    TESSELLATION_CONTROL_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT, VK10.VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT),
    TESSELLATION_EVALUATION_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT, VK10.VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT),
    GEOMETRY_SHADER(VK10.VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT, VK10.VK_SHADER_STAGE_GEOMETRY_BIT),
    FRAGMENT_SHADER(VK10.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, VK10.VK_SHADER_STAGE_FRAGMENT_BIT),
    COMPUTE_SHADER(VK10.VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK10.VK_SHADER_STAGE_COMPUTE_BIT);

    public int pipelineVk;
    public int shaderVk;

    ShaderType(int pipelineVk, int shaderVk) {
        this.pipelineVk = pipelineVk;
        this.shaderVk = shaderVk;
    }
}
