package engine.graphics.vulkan.shader;

import org.lwjgl.vulkan.VK10;

public enum ShaderType {
    VERTEX_SHADER(VK10.VK_PIPELINE_STAGE_VERTEX_SHADER_BIT),
    TESSELLATION_CONTROL_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT),
    TESSELLATION_EVALUATION_SHADER(VK10.VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT),
    GEOMETRY_SHADER(VK10.VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT),
    FRAGMENT_SHADER(VK10.VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT),
    COMPUTE_SHADER(VK10.VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

    public int vk;

    ShaderType(int vk) {
        this.vk = vk;
    }
}
