package engine.graphics.gl.texture;

import org.lwjgl.opengl.*;

public enum GLTextureType {
    TEX_1D(GL11C.GL_TEXTURE_1D),
    TEX_2D(GL11C.GL_TEXTURE_2D),
    TEX_3D(GL12C.GL_TEXTURE_3D),
    TEX_CUBE_MAP(GL13C.GL_TEXTURE_CUBE_MAP),
    TEX_1D_ARRAY(GL30C.GL_TEXTURE_1D_ARRAY),
    TEX_2D_ARRAY(GL30C.GL_TEXTURE_2D_ARRAY),
    TEX_RECTANGLE(GL31C.GL_TEXTURE_RECTANGLE),
    TEX_BUFFER(GL31C.GL_TEXTURE_BUFFER),
    TEX_2D_MULTI_SAMPLE(GL32C.GL_TEXTURE_2D_MULTISAMPLE),
    TEX_2D_MULTI_SAMPLE_ARRAY(GL32C.GL_TEXTURE_2D_MULTISAMPLE_ARRAY),
    TEX_CUBE_MAP_ARRAY(GL40C.GL_TEXTURE_CUBE_MAP_ARRAY);


    public final int gl;

    GLTextureType(int gl) {
        this.gl = gl;
    }
}
